// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0rTqDv5AgYgJO-plS3J7Dpaz2pWSiLVk',
    appId: '1:410139454549:web:42dbfc1e17daedf3b338dc',
    messagingSenderId: '410139454549',
    projectId: 'inventory-management-83c5f',
    authDomain: 'inventory-management-83c5f.firebaseapp.com',
    storageBucket: 'inventory-management-83c5f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAT2CFeOqk8NLLmjvqSqcsig2HEmyGFGfc',
    appId: '1:410139454549:android:2644e9693e2fa672b338dc',
    messagingSenderId: '410139454549',
    projectId: 'inventory-management-83c5f',
    storageBucket: 'inventory-management-83c5f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB18A4co_ueINVrXf8yJB9VZHu32yn6xKo',
    appId: '1:410139454549:ios:b3d634cdfa991a38b338dc',
    messagingSenderId: '410139454549',
    projectId: 'inventory-management-83c5f',
    storageBucket: 'inventory-management-83c5f.firebasestorage.app',
    iosBundleId: 'com.example.inclass15',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB18A4co_ueINVrXf8yJB9VZHu32yn6xKo',
    appId: '1:410139454549:ios:b3d634cdfa991a38b338dc',
    messagingSenderId: '410139454549',
    projectId: 'inventory-management-83c5f',
    storageBucket: 'inventory-management-83c5f.firebasestorage.app',
    iosBundleId: 'com.example.inclass15',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0rTqDv5AgYgJO-plS3J7Dpaz2pWSiLVk',
    appId: '1:410139454549:web:ca0bc92bb972e7e5b338dc',
    messagingSenderId: '410139454549',
    projectId: 'inventory-management-83c5f',
    authDomain: 'inventory-management-83c5f.firebaseapp.com',
    storageBucket: 'inventory-management-83c5f.firebasestorage.app',
  );
}
